### ISSUE TITLE
"Global" Sequences Unexpected

### ISSUE THREAD

**Issue by geofflane** [thoughtbot/ex_machina#120]
This is not a bug per se, but just something surprising that we ran into. Maybe it deserves some documentation? Mostly putting it here to get some feedback.

The sequence is a global Agent that stores the sequence globally for a given atom which was unexpected. The sequences for a given factory are not necessarily sequential. In general, depending on the sequences of a type to be sequential is probably bad of course.

This can cause problems though when the size of the field is limited and you have a lot of lookups, you exponentially grow that sequence and can't figure out why.

i.e. You have multiple models/tables that have some of the same columns
```
  def factory(:lookup_type) do
    %MyModule.LookupType{
      abbreviation: sequence(:abbreviation, &"D#{&1}"),
      name: sequence(:name, &"Name#{&1}"),
    }
  end

  def factory(:another_lookup_type) do
    %MyModule.AnotherLookupType{
      abbreviation: sequence(:abbreviation, &"D#{&1}"),
      name: sequence(:name, &"Name#{&1}"),
    }
  end
```

I think factory_girl works on a sequence per factory, I guess I expected ex_machina to be the same.

**Comment by paulcsmith** [comment]
@geofflane Thank you for bringing this up. I did notice that behavior, but haven't had any issues and couldn't think of any issues. I can see how it might be confusing though :S

However, I am not sure I totally understand the problem with this example. If you use the same sequence name, then it will use that sequences counter. So, what is the issue that arises if you have factories like in your example?

Just to clarify, I'm not against changing this, and I'm definitely for documenting this. I just want to be sure I understand the issues before I make any changes

**Comment by geofflane** [comment]
@paulcsmith In my example if I do
```
create(:dropback_type)
create(:extra_point_type)
```

The first will get an abbreviation of "D1" and the second will get an abbreviation of "D2". My expectation was, that since they are different factories, both would get an abbreviation of "D1" when the first one was created.

I have a database where the abbreviation column is `varchar(2)`. In my example, I can only create 9 lookup types (across all factories) before I run out of space. If I change them to just the integer values I can only create 99 of them (across all lookup types). So in a system with 50 lookup values you functionally "use up" that sequence faster than you would expect.

We worked around it by constructing abbreviations using letters and numbers:
```
  # Generates abbreviations like A1...Z9
  defp abbreviation(n) do
    character = to_string([65 + div(n, 26)])
    number = rem(n, 9) + 1
    "#{character}#{number}"
  end
```
We also worked around it by changing the names of all of our sequences to be unique. Both of which help. Again, just an unexpected thing that we had to work around.

**Comment by paulcsmith** [comment]
@geofflane Oh ok! That clears things up. There are a couple things here. FactoryGirl would do something similar since sequences are defined globally, and not inside a factory: http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Sequences

I think that behavior is ok. However, you are right that it does differ from FactoryGirl in that FactoryGirl resets the sequence at the end (or beginning?) of each test. So each sequence starts from zero for each test.

Here's what I think can be done about this:

1) I'll add a note to the docs/readme that explains the behavior
2) Add `ExMachina.Sequence.reset/0`
3) Instruct users to add this to their `setup` block if they need to reset sequences. They can also do this for all tests by adding it to the `setup` block in their case template (as an example, `ConnCase` in Phoenix). I don't think this needs to be the default since it's more work and for all the apps I've worked on so far, this hasn't been an issue.


In the meantime, I would take a look at the sequence test: https://github.com/thoughtbot/ex_machina/blob/master/test/ex_machina/sequence_test.exs#L7

That's how we reset the sequences for that test. You could do that in your `ConnCase`/`ModelCase`/individual tests to get sequences that start from zero in every test. 

How does that sound? I *believe* this will solve your immediate issue and should also help others in the future once I make those documentation changes

**Comment by geofflane** [comment]
@paulcsmith The reset definitely seems like it would help. Thanks again!

**Comment by paulcsmith** [comment]
@geofflane You're welcome and thanks for pointing this out!

**Comment by paulcsmith** [comment]
Added by #151. Thanks for bringing this up @geofflane
