### ISSUE TITLE
Should `params_for` return a string keyed map?

### ISSUE THREAD

**Issue by drapergeek** [thoughtbot/ex_machina#146]
I just ran into an issue where my unit tests passed fine but my actual code failed due to a misunderstanding about phoenix and it's params. I wrote the test using ExMachina and the `params_for` which returns atom based keys. When working with the bare params in Phoenix, they come through as string keys. Should we make ex_machina follow this same principle so we can test the same way the framework operates?

**Comment by paulcsmith** [comment]
We talked bout this in person and it seems like there is no clear solution. On one hand `params_for` implies that they should be true params, and in Phoenix that means keys are strings. It's possible that outside Phoenix "params" may just be a map of atoms. We're also not sure that switching to string keys would introduce other issues elsewhere.

Since it's not clear what will work we decided to start a branch that converts keys to strings when using `params_for` and then try it out on some new projects to see what works and what doesn't. We may switch to string keys if it seems like the benefits outweigh the cost.

**Comment by pdawczak** [comment]
This is interesting problem! I completely agree with @paulcsmith:

> It's possible that outside Phoenix "params" may just be a map of atoms.

Having `params_for` returning data we could use _everywhere_ like in case of Ruby(/Rails), but here we play with _plain_ data. 

For params in Elixir - if your'e using Phoenix, you might be aware that it deals with _stringified_ version of maps (this, in the end, is something that `params` are), but in almost any other case you want your maps with atoms...

How about introducing additional method, like `string_params_for` or something like that? You could use it in your `controller` tests to build maps with string-keys, and everywhere else standard `params_for` could be used. 💭

**Comment by paulcsmith** [comment]
Yes I think I like the idea of having a `string_params_for`. I generally want atom keys. For example here is someone relying on atom keys: https://github.com/thoughtbot/ex_machina/pull/148#issuecomment-247453163

Adding a *new* function would mean that it won't break anyone's tests and it's a bit more clear to have a second string specific function IMO

**Comment by pdawczak** [comment]
Just a quick note as I thought about it recently, would that make sense to have functions `params_for` and `attrs_for`? Unfortunately, this might not reflect what particular function returns... (_atoms_ vs _strings_)

Initially I was thinking about `params_for` returning the _stringified_ version (as `params` is used as a name in the controllers), but this is exactly what is not backwards compatible...

> and it's a bit more clear to have a second string specific function

Totally agree. Explicitness is one of the most important assets of Elixir

**Comment by jsteiner** [comment]
#168 is getting pretty close, so I'm going to close this issue.
