### ISSUE TITLE
Double import error with multiple factory files

### ISSUE THREAD

**Issue by denispeplin** [thoughtbot/ex_machina#164]
I have two factories, and I need them both in my controller test, but when I try to import them both, I get the error:

```
test/controllers/post_controller_test.exs:11: function insert/1 imported from both ProjectName.PostFactory and ProjectName.SiteFactory, call is ambiguous
```

I've tried to use `except` on second import, and got other errors. Actually, I've tried a lot of ways of splitting files, none of them worked.

As it mentioned in Readme, it is possible to store factories in separate files, is there some "standard" way to do so?

**Comment by paulcsmith** [comment]
Here is an issue that discusses this: https://github.com/thoughtbot/ex_machina/issues/154

The trick is probably to alias them instead of importing. That's probably the simplest solution. LMK if that helps!

**Comment by denispeplin** [comment]
In #154 the problem was with relation from other factory, but the whole thing worked.

I can't figure out how it works basically, given that factories are placed in multiple files.

@paulcsmith, it is impossible to have factories in multiple files and still invoke them like `create(:comment)` instead of `CommentFactory.create(:comment)`, right?

**Comment by paulcsmith** [comment]
@denispeplin Yes that is correct. Aliasing will always work, but you can't import both since the two `create` functions will collide. What I've done in one project was `import` the factory that is most often used, and then alias the other only when needed.

I've got a few ideas for improving this situation, but I'll have to think about it and try a few things first

**Comment by denispeplin** [comment]
Thank you for explanation and for the trick with "most used factory"!
