### ISSUE TITLE
How to deal with associations that refer to other associated fields

### ISSUE THREAD

**Issue by cayblood** [thoughtbot/ex_machina#167]
When I have associations that refer to records created by other associations, I'm having trouble because ex machina seems to be trying to insert some of them twice. For example, the following code seems to try to insert users with the same name twice, resulting in a uniqueness error:

```elixir

# in factory.ex
def user_factory do
  %User {
    name: sequence("User ")
  }
end

def team_factory do
  %Team {
    name: sequence("Team "),
    users: build_pair(:user)
  }
end

def company_factory do
  teams = build_pair(:team)
  users = Enum.flat_map(teams, fn(team) -> team.users end)
  %Company {
    teams: teams,
    users: users
  }
end

# in my test file
company = insert(:company)
```

**Comment by cayblood** [comment]
I was able to do a workaround like so:
```elixir
  users = insert_list(4, :user)
  team1 = insert(:team, users: Enum.take(users, 2))
  team2 = insert(:team, users: Enum.take(users, -2))
  company = insert(:company, teams: [team1, team2], users: users)
```

But it would be nice not to have to create each association separately.

**Comment by pdawczak** [comment]
Hey @cayblood, I've taken a look at issue you've raised and I think what happens is rather correct behaviour.

To understand what's happening (and why it is correct), let's talk through the code with tiny steps (and those will be _manual_, to make it clearer what happens ~more or less~ behind factory functions).

```elixir
# Those will belong to Team 1
u1 = %User{name: "User 1"}
# => %User{id: nil, name: "User 1"}
u2 = %User(name: "User 2"}
# => %User{id: nil, name: "User 2"}

# Those will belong to Team 2
u3 = %User(name: "User 3"}
# => %User{id: nil, name: "User 3"}
u4 = %User(name: "User 4"}
# => %User{id: nil, name: "User 4"}
```

Then, let's take a look at `Team`s:

```elixir
t1 = %Team{name: "Team 1", users: [u1, u2]}
t2 = %Team{name: "Team 2", users: [u3, u4]}
```

and finally, let's bind all of them together within `Company`:

```elixir
c = %Company{
  teams: [t1, t2],
  users: [u1, u2, u3, u4]
}
```

Let's assume, there is no DB index enforcing uniqueness. Once the `c` attempted to be persisted:

```elixir
Repo.insert(c)
```

We would end up with following:

```elixir
%Company{
  id: 1,
  teams: [
    %Team{
      id: 1,
      users: [
        %User{id: 1, name: "User 1"},
        %User{id: 2, name: "User 2"}
      ]
    },
    %Team{
      id: 2,
      users: [
        %User{id: 3, name: "User 3"},
        %User{id: 4, name: "User 4"}
      ]
    }
  ],
  users: [
    %User{id: 5, name: "User 1"},
    %User{id: 6, name: "User 2"},
    %User{id: 7, name: "User 3"},
    %User{id: 8, name: "User 4"},
  ]
}
```

Do you see the problem here now? The names have been generated correctly, but due to immutable nature of Elixir this is what happens:

1. `u1` is as follows: `%User{id: nil, name: "User 1"}`
2. When Elixir attempts to save the `u1` associated to `Team` - it get's created successfully
3. Because Elixir's data is immutable, `u1` is not updated with `id` of newly created `User`. As `u1` is associated to `Company` (via `users` association), another record in DB is created (with the same name)

Your [second approach](https://github.com/thoughtbot/ex_machina/issues/167#issuecomment-251283733) works properly, because you've created users in first place:

```elixir
u1 = Repo.insert(%User{name: "User 1"})
# => %User{id: 1, name: "User 1"}
# ...
```

and the records could be properly associated in DB, because the `id` attributes had values at that point.

As a sidenote - it feels a little bit brittle to keep `users` association both in `Team` and in `Company` (there are no rules that DB could enforce removing a `User` from `Company` once it's removed from `Team`). Did you know that [Ecto.has_many/3](https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3) supports `:through` (similar to [Rails one](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association)).

Please, take a look at example changes [here](https://github.com/thoughtbot/ex_machina/compare/master...pdawczak:pd-sequence-issue) how you could try to use [`:through`](https://github.com/thoughtbot/ex_machina/compare/master...pdawczak:pd-sequence-issue#diff-2a7c386494602d9f18e3ec533f3a6d0cR6) to obtain [the same list of users](https://github.com/thoughtbot/ex_machina/compare/master...pdawczak:pd-sequence-issue#diff-0e2e4fe01782f8bcb93a79112c7fe544R106) (_note, `TeamMember` is used instead of `User` not to get into conflict with already defined models_).

Hope that helps and clarifies things a little bit.

**Comment by cayblood** [comment]
That is helpful. Thanks for the explanation.

**Comment by paulcsmith** [comment]
Thanks for helping clarify the situation with some great examples @pdawczak. I'm going to go ahead and close this
