### ISSUE TITLE
`parms_for` doesn't include custom primary key

### ISSUE THREAD

**Issue by hauleth** [thoughtbot/ex_machina#170]
In my current solution I have primary key that is entered by user and isn't autogenerated. My factory is defined as:

```elixir
  def institution_factory do
    %Onemedical.Institution{
      code: "BMRF", # NOTE: this is primary key
      name: "Black Mesa Research Facility",
      email: "black.mesa@example.com",
      type: "labolatory",
      credits: 1000
    }
  end
```

And `params_for(:institution, %{})` returns:

```elixir
%{about: "", avatar: nil, credits: 1000, email: "black.mesa@example.com",
  inserted_at: nil, inventory: false, name: "Black Mesa Research Facility",
  type: "labolatory", updated_at: nil, ward: false}
```

I would expect that there would be `code` entry also included in params.

**Comment by paulcsmith** [comment]
Right now ExMachina removes the primary key since the record is not actually persisted, and usually that means the primary key is empty. I think we'll keep it like that for now. In the meantime I think you'll need to set the code when using `params_for(:institution, code: "BMRF")`

Maybe we can add an option to include primary keys in `params_for`. What do you think @jsteiner?

**Comment by hauleth** [comment]
Unfortunately setting `code` via params also doesn’t work:

iex(1)> Factory.params_for(:institution, code: "TEST")
%{about: "", avatar: nil, credits: 1000, email: "black.mesa@example.com",
  inserted_at: nil, inventory: false, name: "Black Mesa Research Facility",
  type: "labolatory", updated_at: nil, ward: false}
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by hauleth** [comment]
The same goes for `build` which is even more complex as I cannot create parent of one of my models due to lack of `PRIMARY KEY`.

I would expect that if there is explicitly defined primary key in model template then it should be used no matter what.

**Comment by paulcsmith** [comment]
Yeah that makes sense. Maybe we can keep the primary key if it is not nil. That might solve the problem. If you'd like to submit a PR for that I think that would work well. If not I can tackle it, but I'm not sure when I can get around to ti

**Comment by hauleth** [comment]
@paulcsmith it seems that upstream does that, and there is even test for such situation `test/ex_machina/ecto_test.ex:41` but it seems that `ex_machina` 1.0.2 doesn't have that feature. Also there is something strange as version `0.6.2` is marked as most recent one on GH.

**Comment by paulcsmith** [comment]
@hauleth Ah ok yeah I'll just have to push a new release. Also `0.6.2` is the last published, but not the "latest" version. `0.6.2` makes it so that people that can't use `1.0` can still use `0.6.x` with newer versions of Elixir #145 

I'll publish the latest sometime this week or next. For now you could use master and see if that works
