### ISSUE TITLE
Doesn't work with embeds

### ISSUE THREAD

**Issue by jeroenvisser101** [thoughtbot/ex_machina#195]
Embeds are broken, seems like #73 was overwritten, is this something that could be added back in?

```Factory.insert(:user)
** (RuntimeError) changing embeds with change/2 or put_change/3 is not supported, please use put_embed/4 instead
      (ecto) lib/ecto/changeset.ex:1011: Ecto.Changeset.put_change/7
    (stdlib) lists.erl:1263: :lists.foldl/3
      (ecto) lib/ecto/changeset.ex:325: Ecto.Changeset.change/2
      (ecto) lib/ecto/changeset/relation.ex:152: Ecto.Changeset.Relation.do_change/4
      (ecto) lib/ecto/changeset/relation.ex:237: Ecto.Changeset.Relation.single_change/5
      (ecto) lib/ecto/repo/schema.ex:516: anonymous fn/4 in Ecto.Repo.Schema.surface_changes/4
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/repo/schema.ex:503: Ecto.Repo.Schema.surface_changes/4
```

**Comment by paulcsmith** [comment]
@jeroenvisser101 I don't have a problem with adding it back in, but I don't use embeds much so this isn't a high priority right now. If you (or someone else) wants to take a look at adding it back in/fixing it, that would be great. 

Also it may already be working on `master`, but since I don't use the feature myself I am not sure. **Can you give `master` a try and see if it fixes your issue?**

**Comment by paulcsmith** [comment]
@jeroenvisser101 I added some tests in #200 so embeds *should* work if you use the latest from master. We're working on 2.0 which will include any fixes on master, plus a few other things

**Comment by jeroenvisser101** [comment]
Thanks! I'll try to test these this weekend!

**Comment by jeroenvisser101** [comment]
Sorry for the delay, we tested this and seems to work fine, thanks so much!
