### ISSUE TITLE
Add documentation for `insert` functions

### ISSUE THREAD

**Issue by jsteiner** [thoughtbot/ex_machina#202]
Since these functions are generated dynamically, we don't have any docs for them. Ecto solves this with the `@callback` directive: https://github.com/elixir-ecto/ecto/blob/v2.1.3/lib/ecto/repo.ex#L735

**Comment by schrockwell** [comment]
Additionally, the documentation for the `build` functions should also use the `@callback` spec, since right now the function signature of, for example, `ExMachina.build/3` does not mach the code samples, since it's not the same same as the `build/2` which is injected to a module with `use ExMachina`.
