### ISSUE TITLE
Suggested Test Layouts

### ISSUE THREAD

**Issue by sitch** [thoughtbot/ex_machina#265]
I've been using this pattern a bit and I think it could help out a lot of people new to testing.  Looks like:

```elixir
defmodule MyApp.FactoryContext do
  # I build these via macro, but this is more or less what the generated code could be
  
  import MyApp.Factory
 
  def register_user(context) do
    [user: build(:registered_user, Map.get(context, :user_attrs, %{})]
  end

  # Can chain commands in a CQRS fashion
  def approve_user(%{user: user}) do
    user = MyApp.ApproveUser.apply(user)
    [user: user]
  end

  # OR

  # Override with different factory representations
  def approve_user(context) do
    user = build(:approved_user, Map.get(context, :user_attrs, %{})
    [user: user]
  end
end
```

```elixir
defmodule MyApp.RegisterUserTest do
  import MyApp.ConnCase # also imports MyApp.FactoryContext

  setup [:register_user]

  # Basic test using defaults from the :user factory
  test "it has the name 'Sitch'" %{user: user} do
    assert user.name == "Sitch"
  end
  
  # Test overriding defaults from the :user factory
  @tag user_attrs: %{
    name: "Mike",
  }
  test "it has the name 'Mike'" %{user: user} do
    assert user.name == "Mike"
  end

  describe "user approvals" do

  # Show how to start chaining commands here
   setup [
    :register_user,
    :approve_user,
  ]

    @tag user_attrs: %{
      name: "Josh",
    }
    test "it has the name 'Josh'" %{user: user} do
      assert user.name == "Josh"
      assert user.approved?
    end
  end
```

The thing that's nice about this is that you can recursively define how to establish common database contexts via command chaining in the setup block, but override specific attributes as needed.  

Thoughts?

**Comment by germsvel** [comment]
Hi @sitch, thanks for posting that kind of setup. I tend to prefer being a little more explicit in my test setup within the `test` macro (rather than just having `asserts`) even if that means I have some setup duplication. In other words, I prefer having the [test phases](https://robots.thoughtbot.com/four-phase-test) more clear within each test.

I find that putting too much of the setup away tends to (a) hide complex setup which could be an indicator of highly coupled modules/schemas, and (b) it can lead to difficulty knowing what is and what isn't set up when reading the test or when trying to add a new test. 

But that's just my opinion. I am wondering if you might get more perspectives by posting it somewhere like https://elixirforum.com/?

**Comment by germsvel** [comment]
@sitch I'll close this for now. Let me know if you wanted to keep it open for some reason.
