### ISSUE TITLE
Bulk Inserts

### ISSUE THREAD

**Issue by aditya7iyengar** [thoughtbot/ex_machina#286]
We have been using `ex_machina` for seeding bulk data. I was thinking it would be a good feature to add `insert_bulk` functionality to make that process faster. How does that sound to you?

If this sounds like a feature you guys want, I can work on it in a PR. 

_Thanks for writing this library_ :smile:

**Comment by germsvel** [comment]
Hi @aditya7iyengar, thanks for bringing up this idea. It's interesting you're using `ex_machina` for bulk inserts. Just curious, is this dummy data you're inserting for development? 

Since `ex_machina` is mostly used in tests, I'm not quite sure bulk inserts would be a great feature to add. Instead, what I might do in that scenario is use something like Ecto's [insert_all](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert_all/3). Do you know if that would be good for your use case?

**Comment by germsvel** [comment]
Hi @aditya7iyengar I'm going to close this for now. If this is still something of interest, let me know! Glad to reopen this if the previous comment doesn't make sense for your use case.
