### ISSUE TITLE
Allow optional `attrs` to be passed to factories

### ISSUE THREAD

**Issue by sgtpepper43** [thoughtbot/ex_machina#309]
Right now we just merge `attrs` onto the built object, but we can't use `attrs` when creating the object. Normally this is fine, except when you want to insert the object rather than just build it, or when you have some fancy logic you don't want to duplicate that manipulates the generated fields. Take this example from the docs:
```elixir
def article_factory do
  title = sequence(:title, &"Use ExMachina! (Part #{&1})")
  # derived attribute
  slug = MyApp.Article.title_to_slug(title)
  %MyApp.Article{
    title: title,
    slug: slug,
    # associations are inserted when you call `insert`
    author: build(:user),
  }
end
```
This works great until you do this `build(:article, title: "My Custom Title")`. Now the logic on how to build the slug has to live in two places, and on top of that, you can't even use `insert` unless you're willing to hit the database twice just to insert one object. I know this can be done with strategies, but you can't overwrite the default `build` function, and it kinda just makes sense for this to be a standard implementation. `attrs` could be completely optional, and it would be a pretty straightforward change:

```diff
  def build(module, factory_name, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{})
    function_name = build_function_name(factory_name)
-   if Code.ensure_loaded?(module) && function_exported?(module, function_name, 0) do
+   cond do
+    Code.ensure_loaded?(module) && function_exported?(module, function_name, 1) ->
+      apply(module, function_name, [attrs]) |> do_merge(attrs) 
+    Code.ensure_loaded?(module) && function_exported?(module, function_name, 0) ->
       apply(module, function_name, []) |> do_merge(attrs)
+    true ->
       raise UndefinedFactoryError, factory_name
    end
  end
```

And then you could do
```elixir
def article_factory(attrs) do
  title = Map.get_lazy(attrs, :title, fn -> sequence(:title, &"Use ExMachina! (Part #{&1})") end)
  # derived attribute
  slug = MyApp.Article.title_to_slug(title)
  %MyApp.Article{
    title: title,
    slug: slug,
    # associations are inserted when you call `insert`
    author: build(:user),
  }
end
```

**Comment by germsvel** [comment]
@sgtpepper43 thanks for posting this. I like this. I've been thinking for some time how to provide a lower layer of abstraction for people who want to have more control of the factory. 

I am thinking to do something similar to what you suggest but where we don't merge the `attrs` at all. So I would so something like this, 

```elixir
Code.ensure_loaded?(module) && function_exported?(module, function_name, 1) ->
      apply(module, function_name, [attrs])  
Code.ensure_loaded?(module) && function_exported?(module, function_name, 0) ->
       apply(module, function_name, []) |> do_merge(attrs)
```

This way, if someone wants full control of the factory, they just define it with `/1` arity. The positive side of doing it that way is that it would allow for factories that aren't maps (requested in https://github.com/thoughtbot/ex_machina/issues/271 and https://github.com/thoughtbot/ex_machina/issues/272). 

The downside is that people would have to add `Map.merge/2` or `struct!/2` at the end of their factory definitions if they wanted to merge all the attributes since ExMachina would not longer be doing it for them, 

```elixir
def article_factory(attrs) do
  title = Map.get_lazy(attrs, :title, fn -> sequence(:title, &"Use ExMachina! (Part #{&1})") end)

  slug = MyApp.Article.title_to_slug(title)
  article = %MyApp.Article{
    title: title,
    slug: slug
  }

  struct!(article, attrs)
end
```

Another downside, but I think it would be fine is that I think it might cause confusion and people would define two factories, one with `/0` and one with `/1`, thinking that `build(:factory_name)` would use the  `/0` arity one and `build(:factory_name, attribute: "something")` would use the `/1`, but that would be incorrect and `/0` is never used. 

What do you think?

**Comment by sgtpepper43** [comment]
I'm always a fan of being more explicit, requiring you to merge the attrs yourself if you use the `/1` function wouldn't be a big deal for factories with map, and obviously would be great for factories that aren't. The issue of people mixing the two up on accident could probably be fixed with good documentation (hopefully people read docs?), and since the`/0` function would remain and it would all be backwards compatible, I think it would all work out.

**Comment by germsvel** [comment]
Yeah, I think in the early days, `attrs` were passed but it was confusing so they were removed in https://github.com/thoughtbot/ex_machina/issues/56. The difference is that they were merged after being passed in, so I think that's what caused confusion. Hopefully if we do this, it'll be less confusing. And yeah, good docs will hopefully make a difference.

**Comment by sheharyarn** [comment]
I struggle with the same problem and usually have an extra helper for most factories that does this for me. I think passing in the attrs map is a great idea and would love to see this implemented soon.

**Comment by germsvel** [comment]
Thanks for the offer @sheharyarn. I have a full implementation of this working, but I'm leaning against it now. At least in this format. I'm trying to find a better way to expose this. 

My hesitation comes because I think it'll confuse people. It seems to me that simply changing the function arity causes a change in behavior, since the arguments are no longer merged in at the end. And that is a surprising effect. And allowing for passing arguments _while also_ automatically merging the arguments at the end  has caused issues in the past (see #56, and https://github.com/thoughtbot/ex_machina/issues/54#issuecomment-155192430). 

I think what we'll want to do is actually expose a different function name for those wanting to build a "raw" factory. I don't have a good name for it, but I do think that would make it clear that you need to do your own merging of attributes. 

For example, 

```elixir
def article_factory do 
   # here we'll merge attributes for you
end

# vs

def article_base_factory(attrs) do
   # here we won't do any attribute merging for you
end
```
  
I'm totally open to suggestions on function names for the "base" factory. I do think with a descriptive function name we can open up that lower level to users.

**Comment by sheharyarn** [comment]
Though I think a difference in arity automatically conveys that it is a separate function, I see your point. What we could do is raise an error during compilation if a factory function with both arities exists.

That still might confuse new developers, but I imagine that it'd happen with the a normal factory method and a "raw" factory method as well. If both of them are present, would both be called? Or do we allow only one per factory to be present at a time and raise errors during compilation otherwise?

**Comment by sheharyarn** [comment]
@germsvel Did you make a decision on how to proceed with this? I've been playing around with your previous proposal in my code and pretty happy with the results so far:


```elixir
def history_factory(attrs) do
  post = Map.get_lazy(attrs, :post, fn -> insert(:post) end)
  delta = [
    %{retain: 1},
    %{insert: "Hello", attributes: %{author: post.owner_id}}
  ]

  history =
    %History{
      delta: delta,
      post: post,
      snapshot: post.content,
      organization: post.organization,
      revisions: [%{delta: delta}],
      authors: %{post.owner_id => 1},
      version_from: 1,
      version_to: 2
    }

  struct!(history, attrs)
end
```

**Comment by germsvel** [comment]
Hi @sheharyarn, I'm still trying to figure out how to expose this functionality without causing confusion. If you have thoughts on what we could do, please let me know. I'm definitely looking for thoughts/suggestions/help with this. These are the possible issues I see people running into, 

1. A new user of ExMachina thinking that `build(:article)` would call `article_factory/0` and `build(:article, title: "hello")` would call `article_factory/1`. It seems to me like an easy mistake to make. 
2. A user who used to have a `article_factory/0` all of the sudden needs to further customize the factory and they change it to `article_factory/1`, but they don't know to merge the attributes at the end. All of the sudden tests start breaking _seemingly_ without reason. I think this is a surprising change in behavior from changing the function arity, so I think it'll cause confusion. I would like to try to satisfy the principle of least surprise with this, so I'd rather do something else. 
3. Possibly related to (1), but people defining multiple factories by the same name, one that doesn't take arguments and one that does. Then assuming that they can call one or the other based on particular arguments they pass. That would not be the case in the way I was thinking of implementing this, so probably confusing as well. 

I think the best thing would be to somehow convey the notion to the user that they are using a "raw" factory (meaning ExMachina will not be doing the "usual" stuff for them). I don't know how to convey that well. My thought so far was that by changing the function name at the point of defining the factory (e.g. `def article_base_factory(args)`) we might be able to convey that meaning to the user. But I don't think `_base_factory` makes much sense, so I'm looking for other ideas. And I'm also trying to be cautious as to what words we choose, since that could cause collisions with existing factories for users (e.g. with `_base_factory` a user can no longer have a struct called `%UserBase{}` because that would normally give us `user_base_factory`). 

Maybe a completely new name (instead of "factory") would work (e.g. `def article_core(args)`) but again I am not sure what word would best describe that. Let me know if you have thoughts or ideas!

**Comment by lasseebert** [comment]
I have run into the same issue and also a related issue.

The issue described here is that one wants to alter the given attributes. E.g. set a slug from a title like in the example from the description.

The related issue, is that I sometimes want to do some side-effects based on the final model. E.g. whenever an article is in the database, I also want to add another thing to be in the database, but the other thing is not a db-relation to the article.

Extending on your ideas, perhaps it could be possible to define a preprocessor and a postprocessor.

Something like this (raw sketch):

```elixir
def article_factory do
  %MyApp.Article{
    author: build(:user),
  }
end

def pre_article(attrs) do
  title = Map.get_lazy(attrs, :title, fn -> sequence(:title, &"Use ExMachina! (Part #{&1})") end)
  slug = MyApp.Article.title_to_slug(title)

  attrs
  |> Map.put(:title, title)
  |> Map.put(:slug, slug)
end

def post_article(article) do
  MyApp.save_related_thing(article)
  article
end
```

Then the `pre_*` and `post_*` are optional functions and the factory works the way it used to.

**Comment by mrcasals** [comment]
@lasseebert so whatever you define in the `article_factory` would take precedence over what is set in the `pre_article`, right? Imagine you have the same code as in your example, but you change the factory:

```elixir
def article_factory do
  %MyApp.Article{
    title: "My super title",
    author: build(:user),
  }
end
```

Calling the `article` factory like this, then:

```elixir
article = build(:article, title: "Another title")
article.title # => "Another title"
article.slug # => "use-exmachina-part-0" # the slug is set on `pre_article`, which comes before the factory
```

And this gets more complicated when you need to rely on relations data, which would be set in the factory. To avoid this problem, I think we'd need to run the code *after* the factory, but before the struct is actually built. 

What about, instead of adding pre/post processors, we deal with some kind of "hooks"? Each strategy could set some hooks. For example, `EctoStrategy` could define `before_insert` and `after_insert` hooks, and if `before_insert_article` function is defined then it receives both the article and whatever params you pass it, so you can merge attributes. We could also define a `MemoryStrategy`, that would handle the `build` function (instead of the current `ExMachina` module), and define some `pre_build`/`post_build` callbacks. But it's starting to remind me of Rails ActiveRecord's `after_create` callbacks, which were always a problem in my experience... Leaving the idea here in case someone iterates on it! 😄

**Comment by lasseebert** [comment]
@mrcasals 
I think you got my idea wrong. The pre- and post-functions are always called (if they exist).

So having this in a test:

```elixir
insert(:article, title: "Another title")
```

would behind the scenes do something like this (pseudo-ish code):

```elixir
attrs = pre_article(attrs)
model = insert_article(attrs)
post_article(model)
model
```

So this is kind of like hooks. The `pre-*` can alter the attrs and the `post-` can act on the final model (and possibly return a new model perhaps). Both can have side effects, e.g. saving other stuff to the db.

It gives a simple interface to alter attributes and have side effects when needed.

I only use ExMachina with Ecto, so I don't know if this fits the general scope of ExMachina.

**Comment by lasseebert** [comment]
By the way, I will be happy to help with implementation and/or testing, once a solution has been worked out :)

**Comment by germsvel** [comment]
Hi @lasseebert and @mrcasals, thanks for joining the conversation!  

Let's keep this issue scoped to the idea of passing the attributes into the factory function as outlined in https://github.com/thoughtbot/ex_machina/issues/309#issue-378839835. 

There's another issue talking about adding `before_insert` and `after_insert` callbacks for the EctoStrategy in https://github.com/thoughtbot/ex_machina/issues/251#issuecomment-459455860, which I think may be more in line with what you're talking about.

**Comment by lasseebert** [comment]
@germsvel Ah, didn't see that other issue, sorry. Agreed to keep this issue focused :)

**Comment by germsvel** [comment]
@lasseebert no worries! I'm glad more people are chiming in! It's very helpful to see where the pain points are and how we can improve this library

**Comment by germsvel** [comment]
@sheharyarn and @sgtpepper43,  I've been over other approaches with this, and in the end, I think the best one is to do what we had mentioned previously: pass the attributes as an argument, and require the user to merge their own attributes at the end (if they want to). 

It gives us the most flexibility, and I hope the downsides (the possible confusion) might be fixed with documentation. So it will look like this, 

```elixir
def article_factory(attrs) do
  title = Map.get_lazy(attrs, :title, fn -> sequence(:title, &"Use ExMachina! (Part #{&1})") end)

  slug = MyApp.Article.title_to_slug(title)
  article = %MyApp.Article{
    title: title,
    slug: slug
  }

  merge_atributes(article, attrs)
end
```

**Comment by sheharyarn** [comment]
@germsvel Super happy that this has finally been merged in #333! When can we expect a new release of the `ex_machina` package that includes the new changes?

**Comment by germsvel** [comment]
Hi @sheharyarn I ran out of time yesterday. But I'm hoping sometime over the coming week!

**Comment by germsvel** [comment]
@sgtpepper43 and @sheharyarn a release went out today with these changes. Hope they're useful! https://hex.pm/packages/ex_machina/2.3.0

Please let me know if you find any bugs!
