### ISSUE TITLE
Support Decimal or other structs being casted in `params_for` / `string_params_for`

### ISSUE THREAD

**Issue by sitch** [thoughtbot/ex_machina#332]
Currently if you define:
```elixir
def decimal_factory do
  Decimal.new(25)
end
```
and call
```elixir
Factory.string_params_for(:decimal)
iex> %{"coef" => 25, "exp" => 0, "sign" => 1}
```
Whereas you'd likely be expecting:
```elixir
Factory.string_params_for(:decimal)
iex> "25"
```
Would be nice to support custom struct mapping in the ExMachina.Ecto via passing some custom opts. i.e,:
```elixir
use ExMachina.Ecto, repo: MyApp.Repo, cast: [Decimal => &Decimal.to_string/1]
```
Just need a little metaprogramming to support this

**Comment by germsvel** [comment]
Hey @sitch, 

My expectation of `string_params_for(:decimal)` would be to get `%{"coef" => 25, "exp" => 0, "sign" => 1}`, since that's what the [string_params_for/2](https://hexdocs.pm/ex_machina/ExMachina.Ecto.html#c:string_params_for/2) function is meant to do. 

From the docs, 

> Similar to params_for/2 but converts atom keys to strings in returned map. 

I think what you may be looking for is something like https://github.com/thoughtbot/ex_machina/issues/271, where you can just define a factory that doesn't return a map, so you could make it return a string by doing this, 

```elixir
build(:decimal)
# returns "25"
```

**Comment by germsvel** [comment]
@sitch the latest release of ExMachina, which has #333, should allow you to define a factory that does not return a map, so I think you should be able to accomplish what you want with [non-map factories](https://hexdocs.pm/ex_machina/2.3.0/readme.html#non-map-factories). Let me know if you feel like that didn't address it, and we can reopen this issue. But for now I'll close this.
