### ISSUE TITLE
Remove "only: :test" from README?

### ISSUE THREAD

**Issue by dwarner** [thoughtbot/ex_machina#343]
" For most projects (such as Phoenix apps) this will mean adding :ex_machina to the list of applications in mix.exs."

So, I added
``` 
extra_applications: [:logger, :runtime_tools, :ex_machina]
```
and

```
def deps do
  [
    {:ex_machina, "~> 2.3", only: :test},
  ]
end
```

With the above, tests run just fine, but when I try to run something outside of the test environment, like the phoenix server, I get:
`** (Mix) Could not start application ex_machina: could not find application file: ex_machina.app`

To get the test environment and dev environment, I need to remove `:ex_machina` from extra_applications OR remove `only: test` from the deps section.

Should the README be updated?  Can extra_applications be environment specific?

**Comment by lccezinha** [comment]
Which version of Phoenix are you using?

I have a project here that uses ex_machina and I only had to configure the `deps` function, without any changes in the `extra_applications`

**Comment by germsvel** [comment]
Hi @dwarner. I think you might have missed the little caveat (which I think we should make more prominent) right after the sentences you quoted: 

> And start the ExMachina application. For most projects (such as Phoenix apps) this will mean adding :ex_machina to the list of applications in mix.exs. You can skip this step if you are using Elixir 1.4 or later.

We should probably highlight _You can skip this step if you are using Elixir 1.4 or later._ a little bit more. Elixir 1.4 introduced [application inference](https://github.com/elixir-lang/elixir/blob/v1.4/CHANGELOG.md#application-inference), so that's why it's not needed after 1.4. 

Does that make sense? I think _not including_ `:ex_machina` in your list of `extra_applications` should solve your issue.

**Comment by lccezinha** [comment]
@germsvel make sense for me, my app uses the 1.4.X version, so that is the reason that I was able to create and compile the app without setting any configuration inside `extra_applications`.

**Comment by germsvel** [comment]
I'm gonna go ahead and close this issue. But if you feel like this is still a problem, please let me know! I'd be happy to reopen it.
