### ISSUE TITLE
Don't reproduce FactoryGirl please

### ISSUE THREAD

**Issue by lessless** [thoughtbot/ex_machina#38]
Hello, 

Let's get one thing straight - FactoryGirl is a wicked and brittle: instead of encouraging PORO usage someone decided to take metaprogramming homework onto the next level and created a DSL that  merely resemble the Rails story: it's cool for simple things but requires to learn a language inside a language  to approach to the complexity of real-world applications. And that doesn't even guarantee to cover answer all the questions. 
Why should developers spend time to learn a dialect  if they already knows Ruby? 
Too much of magic kills all the fun (beyond the certain point), and I believe you as a maintainers of the FC know that better then anyone else. 
Please, do not repeat this story with Elixir, do not abuse metaprogramming - use it point-wise and stand by explicitness.
Thanks for all your work and contribution in open-source.

**Comment by halogenandtoast** [comment]
I'm not sure a comment that is along the lines of "please don't make this" is very constructive and doesn't leave us a lot of room to do anything about the problem you are having with this project. I think instead if you had direct suggestions for what does or doesn't work, maybe by providing examples of what you don't currently like and what you'd prefer to see, we could then address them, but as is I'm going to close this issue because there really isn't an actionable item here.
