### ISSUE TITLE
Raise a when invalid attributes are passed to `create` / `build` etc. (use struct!/2)

### ISSUE THREAD

**Issue by jsteiner** [thoughtbot/ex_machina#50]
Elixir will raise an error if you try to pass an unknown key when creating a struct like so:

```
iex(2)> %Foo{invalid: "invalid"}
** (CompileError) iex:3: unknown key :invalid for struct Foo
```

While not every ExMachina factory generates a struct, some do. When we use `build`, we convert the passed data to a map which doesn't raise errors for invalid keys. Would it make sense to look for a `__struct__` field, and if it's there, try to convert it to a struct to raise any errors? 

Elixir 1.2 introduced [`struct!`](http://elixir-lang.org/docs/master/elixir/Kernel.html#struct!/2) which might help.

Is there any other way of doing this?

**Comment by paulcsmith** [comment]
Yeah that's a good point. I think for starters we can check if it's a struct that is returned and use `struct` to override the attributes instead of Map.merge. 

We could also consider getting all the keys from a struct and raising if  any if the overridden attributes aren't in the struct.

I'd rather wait until elixir 1.2 is out and use struct! though

**Comment by paulcsmith** [comment]
I think we can use struct! when we release ExMachina 1.0 and require Elixir 1.2 or greater.
