### ISSUE TITLE
starting ex_machina

### ISSUE THREAD

**Issue by beedub** [thoughtbot/ex_machina#69]
(Newish to elixir, so apologies in advance :smiley:)

The README says to add `ex_machina` to the list of applications. Doesn't this mean that `ex_machina` is started in all envs, not just the test? I've seen a few test-only libraries recommend adding a line to `test_helper.exs` to start the app in tests only. Is this a different use-case?

**Comment by paulcsmith** [comment]
That's a great question! We originally suggested to start the app in the test helper, but recently changed that in this commit: https://github.com/thoughtbot/ex_machina/commit/c70f9b97e26fb291359b6e379cb265cc4b31af07

The reason we changed it is because ExMachina is very useful for generating seed data in other environments. It is also easier for us to suggest that people add it to lib and then include it in all environments by default.

If you want, you can definitely start it only in test, but that is up to you! Does that answer your question?

**Comment by paulcsmith** [comment]
@beedub If that answers your questions, can you let me know and I'll close this issue

**Comment by beedub** [comment]
@paulcsmith it does. I'm still not sure if it's a conventional to start something like this in `production` for example. It unlikely to do any harm in production, but it's also not something I'd think about loading there by default. Is there a conventional elixir way to load in all envs but one like prod?

**Comment by paulcsmith** [comment]
@beedub Yes, as long as you don't use the factory in production you could have a list of apps that does not include `:ex_machina` if the environment is production. 

In this old commit you can see how you would use a different list of apps in different environments: https://github.com/thoughtbot/ex_machina/commit/0aa6d7b62b79287fa20e0951bb8af1a13f811cb2#diff-04c6e90faac2675aa89e2176d2eec7d8L26

So you could pattern match on `:production` and return a different list of apps. I hope that makes sense. Not sure it's worth it, but you can definitely do it this way

**Comment by beedub** [comment]
Makes sense to me. Thanks @paulcsmith for the overview

**Comment by aaronrenner** [comment]
@paulcsmith I was curious about how to only get ex_machina to run in test as well. What do you think about showing both ways (test only and all environments) in the readme?

**Comment by paulcsmith** [comment]
We added more in depth instructions to cover most use cases in this PR https://github.com/thoughtbot/ex_machina/pull/88/files I hope that helps :D
