### ISSUE TITLE
fields_for seems to strip has_many through associations

### ISSUE THREAD

**Issue by paulcsmith** [thoughtbot/ex_machina#93]
``` elixir
fields_for(:post, comments: []) # Results in no goals key
fields_for(:post) |> Map.put(:comments, []) # Sets the results key correctly
```

**Comment by paulcsmith** [comment]
This is caused by https://github.com/thoughtbot/ex_machina/blob/master/lib/ex_machina/ecto.ex#L75. Maybe it makes sense to leave associations and not remove them?

**Comment by wende** [comment]
Not only it'd be cool but it's also a little bit misleading that when you do `params_for(:model)` and you don't have an assoc field that you put there

**Comment by paulcsmith** [comment]
@wende there is a params_with_assocs in ExMachina 1.0 that also includes belongs_to. That might help!

**Comment by wende** [comment]
Yeah. But unfortunately I need `has_many`
I'm inserting an Order with items in it. 
And doing `params_with_assoc(:order)` I expected to have items there. But because they're `has_many` association, they're not there.
And I can't think of a solution to get this without breaking ExMachina's philosophy

**Comment by paulcsmith** [comment]
Ah yes we strip has_many from params in that situation. In this case I would do something like 

params_for(:order) |> Map.put(:order_items, the_items)

Not ideal but might be good for now
